version: 2.1

# Variables

cache_key: &cache_key npm-cache-{{ checksum "package-lock.json" }}

# Configs

lint_config: &lint_config
  requires:
    - install

tests_config: &tests_config
  requires:
    - lint

build_config: &build_config
  requires:
    - lint

deploy_config: &deploy_config
  requires:
    - unit-tests
    - e2e
    - build

feature_config: &feature_config
  filters:
    branches:
      ignore:
        - develop
        - main

dev_config: &dev_config
  filters:
    branches:
      only: develop

prod_config: &prod_config
  filters:
    branches:
      only: main

# Executors

executors:
  node_executor:
    parameters:
      version:
        type: string
        default: '20.11.1'
    docker:
      - image: cimg/node:<< parameters.version >>
    resource_class: medium
  node_browsers_executor:
    parameters:
      version:
        type: string
        default: '20.11.1'
    docker:
      - image: cimg/node:<< parameters.version >>-browsers
    resource_class: medium

# Orbs

orbs:
  browser_tools: circleci/browser-tools@1.4.4
  cypress: cypress-io/cypress@3

# Jobs

jobs:
  install:
    executor: node_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - *cache_key
      - run:
          name: Install packages
          command: npm install
      - save_cache:
          key: *cache_key
          paths:
            - node_modules
  lint:
    executor: node_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - *cache_key
      - run:
          name: Run Lint
          command: npm run lint
  unit-tests:
    executor: node_browsers_executor
    steps:
      - checkout
      - browser_tools/install-chrome
      - restore_cache:
          keys:
            - *cache_key
      - run:
          name: Run unit tests
          command: npm run test -- --no-watch --no-progress
  e2e:
    executor: cypress/default
    steps:
      - browser_tools/install-chrome
      - cypress/install:
          install-browsers: false
      - cypress/run-tests:
          cypress-command: npx cypress run --browser chrome
          start-command: npm run start
  build:
    executor: node_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - *cache_key
      - run:
          name: Build dev
          command: npm run build:dev
  build-prod:
    executor: node_executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - *cache_key
      - run:
          name: Build prod
          command: npm run build:prod

# Workflows

workflows:
  feature:
    jobs:
      - install:
          <<: *feature_config
      - lint:
          <<: [*feature_config, *lint_config]
      - unit-tests:
          <<: [*feature_config, *tests_config]
      - e2e:
          <<: [*feature_config, *tests_config]
      - build:
          <<: [*feature_config, *build_config]
  dev:
    jobs:
      - install:
          <<: *dev_config
      - lint:
          <<: [*dev_config, *lint_config]
      - unit-tests:
          <<: [*dev_config, *tests_config]
      - e2e:
          <<: [*dev_config, *tests_config]
      - build:
          <<: [*dev_config, *build_config]
  prod:
    jobs:
      - install:
          <<: *prod_config
      - lint:
          <<: [*prod_config, *lint_config]
      - unit-tests:
          <<: [*prod_config, *tests_config]
      - e2e:
          <<: [*prod_config, *tests_config]
      - build:
          <<: [*prod_config, *build_config]
